---
title: "Data Story Clinic"
output:
  tufte::tufte_handout:
    toc: no
    toc_depth: 1
    latex_engine: xelatex
  tufte::tufte_html:
    toc: yes
    toc_depth: 1
---

#\textcolor{blue}{Statistics and the Logic of Discovery}  

## Introduction
Crest recently began advertising their newest product -- *Gum Detoxify Deep Clean Toothpaste*.  The company claims that Gum Detoxify "has an activated foam formula ... to neutralize harmful plaque bacteria even around the gum line, for clinically proven healthier gums."

`r tufte::margin_note("Question 1 -- What is the difference between an advertising claim and scientific knowledge?  Or is there a difference?")`

Recently, Ginger Vitas, a vice-president at *Consumer Reports*, asked your lab to independently verify this claim.  The problem, as Ginger puts it, is that a lot of dental product research is funded by big corporations with vested interests in achieving positive outcomes.

In this clinic, we will walk you through the basics of the scientific method and the process a scientist would undertake to either confirm or refute a claim like the one being made by Crest, using nothing more than basic statistics.

With your existing knowledge of microbiology, you know that a subset of bacterial species have been linked to gingivitis, cavities, and oral bleeeding.  Thus you know that a reduction in "bad bugs"" is a good thing, resulting in a healthier mouth.  

So if *Gum Detoxify* works, as Crest claims, we should observe less gingivitis and bleeding in populations that use it on a regular basis.  In other words, the product will prove effective at eliminating bad bacteria and that, in turn, should promote healthier gums and teeth.

`r tufte::margin_note("Question 2 -- How would you design an experiment to justify or invalidate Crest's claims?")`

## Study Design
The most basic research design is when an investigator compares two groups.  In statistics, these are called the the *control* and *treatment* groups.  As its name suggests, our treatment group consists of individuals who use *Gum Detoxify* while our control group consists of individuals who use a competing product that does not have stannous fluoride in it.  Or do not brush at all.

The outline of a possible research design is now coming into view.  The first step is to state our *null* and *research* hypotheses.  The research hypothesis - also known as the alternative hypothesis - states what happens when the treatment works.  The null hypothesis, on the other hand, states what happens when there is no observable treatment effect, when the treatment does not work.  It is considered good form to write both out, at the start of a research project.

`r tufte::margin_note("Question 3 -- What is the null and alternative hypotheses for the stannous fluoride research project?  Write one sentence for each one.")`

In the research literature, the symbol for the null hypothesis is $H_{0}$, spoken as H naught or H zero.  The alternative hypothesis is usually written as $H_{a}$.  

With our two hypotheses defined, we can now recruit study participants, drawing a *sample* from the *population* of potential candidates.  If done well, our study participants will *represent* the population from which they were drawn -- by age, race, income, gender, and so forth.

Our next step is to randomly assign each study participant to either the control or treatment group, a process that can be done easily in R.  We also need to select an appropriate study duration.  Do we want to compare the two groups for 6 months, a year, or some other length of time?  

And finally, we need to select an appropriate instrument to measure the oral health of our participants.  In this case, two indices are probably needed, one to measure gum health and a second to score bleeding. 

## Conducting the Research
Most research studies take a *baseline* measurement of the variables of interest, at project start.  The following table summarizes the results for our control and treatment groups.

Gingival index

Control (*N* = 67) | Sn$F_{2}$/SHMP (*N* = 65)
-------------------| --------------------------
mean +/- SD        | mean +/- SD
2.00 +/- 0.13      | 2.00 +/- 0.13

Gingival bleeding index

Control (*N* = 67) | Sn$F_{2}$/SHMP (*N* = 65)
-------------------| --------------------------
mean +/- SD        | mean +/- SD
10.90 +/- 3.92     | 10.86 +/- 4.93

`r tufte::margin_note("Question 4 -- What does N , mean +/-, and SD stand for in these two tables?")`

Let's briefly review some basic statistics vocabulary.  *N* is the number of observations.  From the two tables, we see that the sample size for the two groups differs by 2.  SD stands for Standard Deviation, a measure of the spread of the data about the mean.  (We don't have time in this session to delve into the details.)  And finally, mean is a synonym for the average of the scores and is calculated by summing the scores and then dividing by *N*.  The mathematical notation looks like this: $M = \frac{\sum X}{N}$

`r tufte::margin_note("Question 5 -- If the mean or standard deviation had differed significantly between these two samples, what would that have told us?")`

With baseline scores obtained, we can now begin the study, being diligent to monitor participant adherence to the protocol.  That is, we want to ensure that participants in the treatment group only use Sn$F_{2}$ infused toothpaste while those in the control group brush with a product that does not contain this chemical.  

## The Two Sample T-Test
After 3 months and then again after 6, we'll score participants in the two groups, using our gingival and bleeding indices.  Earlier, $H_{a}$ was stated mathematically as: $\mu_t < \mu$.  In English, our alternate hypothesis states that the population of people who use a stannous fluoride toothpaste will obtain lower gingival/bleeding scores than the population of people using products that lack this ingredient.

The gingival/bleeding scores obtained at 3 months and then at 6 months are listed in the tables below.

Gingival index

Control (*N* = 67)  | Sn$F_{2}$/SHMP (*N* = 65)
------------------- | --------------------------
mean +/- SD         | mean +/- SD
3 mo 1.97 +/- 0.15  | 1.84 +/- 0.17
6 mo 1.90 +/- 0.21  | 1.58 +/- 0.31

Gingival bleeding index

Control (*N* = 67)  | Sn$F_{2}$/SHMP (*N* = 65)
------------------- | --------------------------
mean +/- SD         | mean +/- SD
3 mo 8.51 +/- 4.77  | 5.62 +/- 4.23
6 mo 8.53 +/- 4.48  | 5.08 +/- 4.89

`r tufte::margin_note("Question 6 -- Do these numbers confirm or disconfirm our alternate hypothesis?")`

A cursory glance at these numbers indicates that participants in our treatment group have lower mean values.  Our research hypothesis appears to be true -- regular usage of *Gum Detoxify* reduces gum inflammation and bleeding.  But can we be sure?  How do we definitively rule out the null hypothesis, the idea that our treatment numbers are the product of pure chance (sampling error)?  If we ran the experiment again and observed little, if any, difference between our control and treatment groups, that would tend to support the null hypothesis.  However, experiments are expensive and we'd like to come to a conclusion with the data collected up to this point.

What we need is a statistical test that allows us to determine if the observed distance between the control and treatment means is large enough to be considered *significant*.  Or put another way, is it highly unlikely (improbable) that the observed difference is due to chance?  Remember: our goal here is to rule out chance as a possible explanation for this difference.

In this case, the two sample t-test is an excellent choice.  William Gossett created the "student's t-test" in the early 1900's.  As an employee of the Guiness Brewing Company, Gossett was not permitted to publish anything under his own name so he chose "student" as a pseudonym.

## The T-Test Simulation
The best way to understand the two sample t-test is to see it in action.  So let's run the numbers through our t-test simulator.

After entering numbers for both our control and treatment groups, the simulator first graphs the distributions of the two groups, runs the two sample t-test, and then graphs the t-distribution with both the p and t values provided.

As its name suggests, a t-test calculates a *t* value.  This number is "a measure of the size of the difference between two groups relative to the variation in the sample data.  Put another way, T is simply the calculated difference represented in units of standard error.  The greater the magnitude of *t*, either positive or negative, the greater the evidence against the null hypothesis that there is no significant difference.  Conversely, the closer T is to 0, the more likely there isn't a significant difference." 

For every *t* value, the probability (p-value) of it occuring can be calculated.  For example, the probability of obtaining a t-value of 2.8 is 0.006.  Thus a *p* value is the probability of getting an obtained value or a more extreme value assuming the null hypothesis is true.  It is used by researchers to determine whether or not they should reject a null hypothesis (Carlson, p. 162).

## Decision Time
With all of the evidence in-hand, it's time to make a decision.  Do we reject or fail to reject the null hypothesis?  The null hypothesis, in this case, is the claim that stannous-fluoride toothpaste is no better than regular toothpaste at reducing gum inflammation and bleeding.  In other words, the results obtained from our study are due to chance and sampling error.

`r tufte::margin_note("Question 7 -- Why do we never accept the null hypothesis?")`

At this point, an important point needs to be kept in mind.  One never accepts the null hypothesis.  Rather, one *rejects* or *fails to reject* it.  Furthermore, rejecting a null hypothesis does not conclusively prove that the alternate hypothesis is true.  There is always the possibility of mistakenly rejecting a null hypothesis and claiming a treatment effect when none actually occurred.  

The *alpha* level quantifies the level of risk we're willing to accept, of rejecting the null hypothesis when it is true.  This is known as a *Type I* error.  It does so by setting the cutoff values of the rejection region(s).  Thus an *alpha* level of 0.05 indicates that we're willing to accept the risk of committing a *Type I* error in 5% of cases.  To reduce that risk, we would simply reduce the alpha level to possibly 1% or lower.  But doing so comes at a cost - we must increase the number of study participants which, in turn, increases the cost of the research project. 

`r tufte::margin_note("Question 8 -- Given these results, what can we conclude about the claims Crest has made for Gum Detoxify?  Does the evidence support or disconfirm the claim that stannous-fluoride infused products like Gum Detoxify reduce gum inflammation and bleeding?")`


## Reference Links

* [Crest Detoxify](https://crest.com/en-us/products/crest-gum-detoxify-deep-clean-toothpaste)
* [MiniTab T & P-Values](http://blog.minitab.com/blog/statistics-and-quality-data-analysis/what-are-t-values-and-p-values-in-statistics)


